# Python科学运算2:矢量化操作与广播运算（练习版）
> 请在空格单元格输入


In [1]:
# 导包
import numpy as np

## 矢量化操作
数据在不需要编写循环的情况下就可以进行批量运算，这就叫矢量化操作
### 加法

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
# 请计算相加


In [3]:
arr1 = np.array([[1,2,3,4],[-3,2,4,9]])
arr2 = np.array([[5,6,7,8],[4,5,1,-10]])
# 请计算相加

### 减法


In [4]:
# 测试arr2-arr1

### 乘法

In [5]:
# 测试arr1*arr2

In [6]:
# 测试 5*arr1

### 除法

In [7]:
# 测试arr1/arr2

### 基本的索引和切片操作

In [8]:
# 初始化
arr =  np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 索引第三个

In [10]:
# 访问4及以后的元素

In [11]:
# 将一个标量的值赋这一个切片时，该值会自动的传播到整个区域，并且直接影响原数据的值
# 将 arr 前5个数改为 3


In [12]:
# 如果不想影响原数据操作
# 使用copy


In [13]:
# 访问2维数组
arr3 = np.array([[1,2,3,4],[-3,2,4,9]])
arr3

array([[ 1,  2,  3,  4],
       [-3,  2,  4,  9]])

In [14]:
# 读取第二行 [-3,  2,  4,  9]


In [15]:
# 读取第二行第一个


### 比较运算
- 在之前我们学习多条件运算时，我们使用的是and 和 or
- 使用numpy对象进行多条件的比较运算时，不能使用and和or
- 必须使用 &（and） 和 ｜（or）

In [16]:
names = np.array(['John','Tony','Jackie','Ben'])
names

array(['John', 'Tony', 'Jackie', 'Ben'], dtype='<U6')

In [17]:
names == "Tony"

array([False,  True, False, False])

In [18]:
# 选择 同时为 Tony 和 Ben

In [23]:
# 选择 Tony 或 Ben

### 花式索引（fancy indexing）
是一个NumPy中的术语，它指的是利用整数数组来进行索引的方式

In [20]:
# 声明一个8*4的空的列表
arr = np.empty((8,4))
# 给列表赋值
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [21]:
# 以一个特定的顺序来选取行中的子集，我们传入一个用于指定顺序的整数列表，或数组
# 这里也可以使用负数来进行索引
# 获取第5，2，6，0行

In [24]:
arr = np.arange(32)
arr
# 请使用 reshape 形成 8*4的列表

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [23]:
# 选取第2，6，8，3行
arr[[1,5,7,2]]
# 选去第2行的第1个，第6行第4个，第8行第2个，第3行第三个


array([1, 5, 7, 2])

In [25]:
# 行和列同时进行花式索引操作
# 自己试一试吧

### 转置操作

In [27]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
# 使用transpose 

In [29]:
# 使用T

### numpy的降维操作

In [30]:
arr = np.array([[1,100,1000],[2,200,2000],[3,300,3000]])
arr

array([[   1,  100, 1000],
       [   2,  200, 2000],
       [   3,  300, 3000]])

In [31]:
# 默认排序的降维
# ravel


In [32]:
# reshape

In [33]:
# flatten

#### 改变排序模式的降维操作

In [34]:
# 使用ravel order

In [35]:
# 使用reshape order

In [36]:
# 使用flatten order

#### 降维以后值的修改

In [38]:
arr = np.array([[1,100,1000],[2,200,2000],[3,300,3000]])
arr.flatten()

array([   1,  100, 1000,    2,  200, 2000,    3,  300, 3000])

In [39]:
# flatten 方法降维之后对值修改不改变原数据
arr.flatten()[0] = 200
arr

array([[   1,  100, 1000],
       [   2,  200, 2000],
       [   3,  300, 3000]])

In [40]:
# ravel 方法降维之后对值修改改变原数据
# 请测试

In [41]:
# reshape 方法降维之后对值修改改变原数据
# 请测试

### NumPy 堆叠操作

In [42]:
arr1 = np.array([[1,100,1000],[2,200,2000],[3,300,3000]])
arr2 = np.array([[-12,321,3332]])

In [43]:
# 纵向堆叠

In [44]:
# row_stack

In [45]:
arr3 = np.array([[5],[6],[7]])
arr3

array([[5],
       [6],
       [7]])

In [46]:
# 横向堆叠

In [47]:
# column_stack

## 广播运算


In [49]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(101,113).reshape(3,4)

In [50]:
# 这不是广播运算，因为其纬度一致
arr1+arr2

array([[101, 103, 105, 107],
       [109, 111, 113, 115],
       [117, 119, 121, 123]])

In [52]:
arr3 = np.arange(60).reshape(5,4,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [54]:
arr4 = np.arange(12).reshape(4,3)
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### 纬度不一致，但是末尾的纬度值是一致的

In [55]:
# arr3 + arr4

In [56]:
arr5 = np.arange(4).reshape(4,1)
arr5

array([[0],
       [1],
       [2],
       [3]])

In [58]:
# arr3 + arr5

In [61]:
# 自动补齐
arr1 = np.arange(12).reshape(4,3)
arr2 = np.array([1,2,3])
# arr1+arr2

#### 不能广播运算的情况

In [62]:
arr1 = np.arange(60).reshape(5,4,3)
arr2 = np.arange(8).reshape(4,2)
# arr1 + arr2

## 条件逻辑转数组
- x if condition else y 
- 当条件condition成立的时候，表达式返回的值是x,不成立的时候返回的是y
- np.where 一般用于根据一个数组产生一个新的数组

In [63]:
arr1 = np.array([1.1,1.2,1.3])
arr2 = np.array([7.1,2.4,3.5])
condition = np.array([True,False,True])

# zip的参数是可迭代的对象
# zip就会将对象中对应的元素打包成一个个的元组，然后返回由这些元组组成的列表
# (arr1) if (condition) else (arr2)

In [64]:
# 使用where

### 值的替换

In [66]:
# 随机生成
arr = np.random.randn(4,4)
arr

array([[-0.9495325 ,  0.4628704 , -1.19209101, -0.69387206],
       [-0.44094781,  1.35353996,  3.06553243,  0.56104829],
       [ 0.08776012,  1.18433784, -0.0816703 ,  0.78551257],
       [ 0.02899248,  2.33851524,  1.08806858,  0.8443345 ]])

In [67]:
# np.where 支持3个参数，第一个参数是条件
# 第二个参数是条件成立的时候返回的值
# 第三个参数是条件不成立的时候返回的值
# result = np.where(arr > 0.2,2,-2)
# result

In [68]:
# result = np.where(arr > 0.2,2,arr)
# result

# 下一节：时间戳