# Python科学运算2:矢量化操作与广播运算

In [3]:
# 导包
import numpy as np

## 矢量化操作
数据在不需要编写循环的情况下就可以进行批量运算，这就叫矢量化操作
### 加法

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr1 + arr2

array([ 6,  8, 10, 12])

In [14]:
arr1 = np.array([[1,2,3,4],[-3,2,4,9]])
arr2 = np.array([[5,6,7,8],[4,5,1,-10]])
arr1 + arr2

array([[ 6,  8, 10, 12],
       [ 1,  7,  5, -1]])

### 减法

In [15]:
arr1-arr2

array([[-4, -4, -4, -4],
       [-7, -3,  3, 19]])

### 乘法

In [16]:
arr1*arr2

array([[  5,  12,  21,  32],
       [-12,  10,   4, -90]])

In [20]:
5 * arr1

array([[  5,  10,  15,  20],
       [-15,  10,  20,  45]])

In [17]:
### 除法

In [18]:
arr1 / arr2

array([[ 0.2       ,  0.33333333,  0.42857143,  0.5       ],
       [-0.75      ,  0.4       ,  4.        , -0.9       ]])

### 基本的索引和切片操作

In [23]:
# 初始化
arr =  np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# 索引第三个
arr[3]

3

In [25]:
# 访问4及以后的元素
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [26]:
# 将一个标量的值赋这一个切片时，该值会自动的传播到整个区域，并且直接影响原数据的值
arr[0:4] = 9
arr

array([9, 9, 9, 9, 4, 5, 6, 7, 8, 9])

In [29]:
# 如果不想影响原数据操作
# 使用copy
a = arr.copy()
a

array([9, 9, 9, 9, 4, 5, 6, 7, 8, 9])

In [30]:
# 访问2维数组
arr3 = np.array([[1,2,3,4],[-3,2,4,9]])
arr3

array([[ 1,  2,  3,  4],
       [-3,  2,  4,  9]])

In [31]:
# 读取第一行
arr3[0]

array([1, 2, 3, 4])

In [33]:
# 读取第二行第四个
arr3[1][3]

9

In [35]:
# 第二种方式
arr3[1,3]

9

### 比较运算
- 在之前我们学习多条件运算时，我们使用的是and 和 or
- 使用numpy对象进行多条件的比较运算时，不能使用and和or
- 必须使用 &（and） 和 ｜（or）

In [36]:
names = np.array(['John','Tony','Jackie','Ben'])
names

array(['John', 'Tony', 'Jackie', 'Ben'], dtype='<U6')

In [37]:
names == "Tony"

array([False,  True, False, False])

In [39]:
# 选择 同时为 Tony 和 Ben
(names == "Tony") & (names == "Ben")

array([False, False, False, False])

In [40]:
# 选择 Tony 或 Ben
(names == "Tony") | (names == "Ben")

array([False,  True, False,  True])

### 花式索引（fancy indexing）
