# Python科学运算1:初识Series与NumPy(练习版)
> 请在空格单元格中填写代码

## Pandas的Series数据类型
### 导入pandas包

In [2]:
# 查询 df 的类型为 Dataframe

### 读取 age 列的数据

In [3]:
# 查询 age 列的数据类型为 Series

### 声明一个Series数据类型

### 单独获取索引和值

In [4]:
# value

In [5]:
# index

### 自定义索引操作

In [6]:
# 通过索引获取值

### 声明Series索引的第二种方法

In [7]:
d = {'a':10000,'b':20000,'c':30000} # 字典类型
# 补全剩下的声明

#### 结论：我们可以把一个字典类型的数据，直接变成Series类型

In [8]:
# 根据自己的需求，取出字典对应的值进行Series数据类型的转换
# 取 索引 a 和 b
keys = ['a','c']
# 补全剩下

### 发现缺失值

In [9]:
d = {'a':20000,'b':None,'c':30000}
obj = pd.Series(d)
obj

a    20000.0
b        NaN
c    30000.0
dtype: float64

In [11]:
# 使用isnull查询 
# 第一种

# 第二种
# pd.isnull(obj)

a    False
b     True
c    False
dtype: bool

In [12]:
# 使用notnull

## 算数运算

In [15]:
d1 = pd.Series([1.3,1.5,2.6,-3.5],index = ['e','b','c','d'])
d1

a    1.3
b    1.5
c    2.6
d   -3.5
dtype: float64

In [16]:
d2 = pd.Series([-1.3,-1,-2.5,3.9,9.8],index = ['a','b','c','d','e'])
d2

a   -1.3
b   -1.0
c   -2.5
d    3.9
e    9.8
dtype: float64

### 两个series的加法

In [17]:
# 两个Series在进行运算的时候，不重叠的地方是空值，重叠的地方进行估算

## pandas读取超大文件时分块操作
python 处理文件时，读取的是硬盘上的资源，而不需要把数据全部直接加载到内存中

In [18]:
df = pd.read_csv("executive.csv")
df

name:ID sex  age  :LABEL
0        谢永林   男   50  people
1        胡跃飞   男   56  people
2         刘勇   男   49  people
3        朱季成   男   37  people
4        张丕杰   男   57  people
...      ...  ..  ...     ...
5645     朱新宏   男   58  people
5646      江津   女   55  people
5647     徐文苏   男   41  people
5648     刘志平   女   55  people
5649     林茂德   男   62  people

[5650 rows x 4 columns]

In [19]:
# nrows 参数的作用就是限制读取多少行
# 要求读取前120行


In [20]:
# 使用chunksize读取

# 然后使用for循环去每块每块地去处理（chunk的type是DataFrame）

### 导入NumPy库
- 命令行： pip install numpy
- jupyter: !pip install numpy
- anaconda: 无需

In [32]:
# 先定义一个列表
data = [1,2,3,4]
# 再定一个列表对象


In [33]:
# 用shape查看纬度

In [34]:
# 用dtype查看数据类型

In [35]:
# 将 data 重复12次 存入对象


In [36]:
# 查看n2的shape和dtype

### 嵌套序列：由一组等长列表组成的列表

In [37]:
# array([[1, 2, 3, 4],
#       [5, 6, 7, 8]])
# 打印出上述列表对象


In [38]:
# 查看 shape ndim(纬度) dtype

### 类型推断：numpy会对数据类型进行一个较为合理的推断

In [39]:
arr = [["1","2",3,4],[5,6,7,8]]
arr2 = np.array(arr)
arr2

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U1')

In [41]:
# 查看 dtype
# <u1 unicode类型 字符串

In [42]:
arr = [[1,2.2,3,4],[5,6,7,8]]
arr2 = np.array(arr)
arr2

array([[1. , 2.2, 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [43]:
# 查看 dtype
# float 浮点数

### numpy指定长度数组的创建

In [48]:
# 创建长度为8，默认值为0的数组
# zeros

In [49]:
# 创建长度为14，默认值为1的数组
# ones

In [50]:
# 创建3*4，默认值为1的数组

In [51]:
# 创建空数组
# 注意 − 数组元素为随机值，因为它们未初始化。

### arange 是range函数的数组版本

In [53]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [54]:
i = range(10)
type(i)

range

In [55]:
i

range(0, 10)

In [56]:
# 输出一个arange 
# arange = array range


### 数据类型转换

In [58]:
arr = np.array([1.2,1.6,1.8,-2.3,-5.8])
arr

array([ 1.2,  1.6,  1.8, -2.3, -5.8])

In [60]:
arr.dtype
# float32/float64 双精度浮点数

dtype('float64')

In [61]:
# 转换为 int 
# int32 32位整型占4个字节
# int64 64位整形占8个字节

# 下一节 矢量化操作与广播运算