# Python科学运算1:初识Series与NumPy
## Pandas的Series数据类型
### 导入pandas包

In [3]:

import pandas as pd
df = pd.read_excel('data_excel.xlsx')
df


/Users/haoyuexu/opt/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


id  age  place
0   1   11     21
1   2   12     22
2   3   13     23
3   4   14     24
4   5   15     25
5   6   16     26
6   7   17     27
7   8   18     28
8   9   19     29
9  10   20     30

In [4]:
# 查询 df 的类型为 Dataframe
type(df)

pandas.core.frame.DataFrame

### 读取 ID 列的数据


In [5]:
df['id']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [6]:
# 查询 id 列的数据类型为 Series
type(df['id'])

pandas.core.series.Series

### 声明一个Series数据类型

In [7]:
obj = pd.Series([1,23,14,34,22,84])
obj

0     1
1    23
2    14
3    34
4    22
5    84
dtype: int64

### 单独获取索引和值

In [8]:
obj.values

array([ 1, 23, 14, 34, 22, 84])

In [9]:
obj.index

RangeIndex(start=0, stop=6, step=1)

### 自定义索引操作

In [11]:
df2 = pd.Series(['a','b','c','d'], index=[4,5,6,7])
df2

4    a
5    b
6    c
7    d
dtype: object

In [13]:
#通过索引获取值
df2[4]

'a'

### 声明Series的第二种方法

In [14]:
d = {'a':10000,'b':20000,'c':30000}
obj = pd.Series(d)
obj

a    10000
b    20000
c    30000
dtype: int64

#### 结论：我们可以把一个字典类型的数据，直接变成Series类型

In [17]:
# 根据自己的需求，取出字典对应的值进行Series数据类型的转换
keys = ['a','c']
obj2 = pd.Series(d,index = keys)
obj2

a    10000
c    30000
dtype: int64

### 发现缺失值

In [19]:
d = {'a':None,'b':20000,'c':30000}
obj = pd.Series(d)
obj

a        NaN
b    20000.0
c    30000.0
dtype: float64

In [20]:
obj.isnull()

a     True
b    False
c    False
dtype: bool

In [21]:
pd.isnull(obj)

a     True
b    False
c    False
dtype: bool

In [22]:
pd.notnull(obj)

a    False
b     True
c     True
dtype: bool

## 算数运算

In [31]:
d1 = pd.Series([1.3,1.5,2.6,-3.5],index = ['e','b','c','d'])
d1

e    1.3
b    1.5
c    2.6
d   -3.5
dtype: float64

In [32]:
d2 = pd.Series([-1.3,-1,-2.5,3.9,9.8],index = ['a','b','c','d','e'])
d2

a   -1.3
b   -1.0
c   -2.5
d    3.9
e    9.8
dtype: float64

### 两个series的加法

In [34]:
# 两个Series在进行运算的时候，不重叠的地方是空值，重叠的地方进行估算
d1+d2

a     NaN
b     0.5
c     0.1
d     0.4
e    11.1
dtype: float64

## pandas读取超大文件时分块操作
python 处理文件时，读取的是硬盘上的资源，而不需要把数据全部直接加载到内存中

In [37]:
# 以前的做法
df = pd.read_csv("executive.csv")
df

name:ID sex  age  :LABEL
0        谢永林   男   50  people
1        胡跃飞   男   56  people
2         刘勇   男   49  people
3        朱季成   男   37  people
4        张丕杰   男   57  people
...      ...  ..  ...     ...
5645     朱新宏   男   58  people
5646      江津   女   55  people
5647     徐文苏   男   41  people
5648     刘志平   女   55  people
5649     林茂德   男   62  people

[5650 rows x 4 columns]

In [41]:
# nrows 参数的作用就是限制读取多少行
e = pd.read_csv("executive.csv", nrows = 120)
e

name:ID sex  age  :LABEL
0       谢永林   男   50  people
1       胡跃飞   男   56  people
2        刘勇   男   49  people
3       朱季成   男   37  people
4       张丕杰   男   57  people
..      ...  ..  ...     ...
115     张新育   男   64  people
116     朱春林   男   58  people
117     邰正彪   男   54  people
118     邹志强   男   55  people
119      李春   男   38  people

[120 rows x 4 columns]

In [42]:
f = pd.read_csv('executive.csv',chunksize = 200)
f

In [43]:
# 然后使用for循环去每块每块地去处理（chunk的type是DataFrame）
for i in f:
    print(i)

    name:ID sex  age  :LABEL
0       谢永林   男   50  people
1       胡跃飞   男   56  people
2        刘勇   男   49  people
3       朱季成   男   37  people
4       张丕杰   男   57  people
..      ...  ..  ...     ...
195     钱震斌   男   59  people
196     杨振华   男   54  people
197      周中   男   51  people
198      张曦   男   44  people
199     符冠华   男   55  people

[200 rows x 4 columns]
    name:ID sex  age  :LABEL
200     黄国宏   男   49  people
201      高波   男   44  people
202     罗叶兰   女   41  people
203      张兵   男   47  people
204     王军华   男   57  people
..      ...  ..  ...     ...
395     柯生灿   男   35  people
396     董凤亮   男   46  people
397      王臻   女   38  people
398     李建勇   男   62  people
399     俞敏亮   男   61  people

[200 rows x 4 columns]
    name:ID sex  age  :LABEL
400     徐永模   男   62  people
401     李晋昭   男   56  people
402      徐千   男   56  people
403     邵晓明   男   60  people
404     陶云鹏   男   48  people
..      ...  ..  ...     ...
595     郑洪霞   女   47  people
596     曾文光   男   50  pe

## NumPy 库
- NumPy 其实就是一个多维的数组（列表）对象
- 每一个数组对象都有 shape方法 和 dtype方法
- shape 属性表示获取到列表的纬度
- dtype 属性表示获取到列表的类型


### 导入NumPy库
- 命令行： pip install numpy
- jupyter: !pip install numpy
- anaconda: 无需

In [44]:
import numpy as np

In [46]:
# 列表的数据类型
data = [1,2,3,4]
data

[1, 2, 3, 4]

In [47]:
# 一个列表对象
n = np.array(data)
n

array([1, 2, 3, 4])

In [48]:
# 查看纬度
n.shape

(4,)

In [49]:
# 查看数据类型
n.dtype

dtype('int64')

In [50]:
# 将 data 重复10次 存入对象
n2 = np.array(data*10)
n2

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [51]:
# 查看n2的shape和dtype
n2.shape

(40,)

In [52]:
n2.dtype

dtype('int64')

### 嵌套序列：由一组等长列表组成的列表

In [55]:
arr = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(arr)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
# 查看 arr2 的 shape ndim(纬度) dtype
arr2.shape

(2, 4)

In [57]:
arr2.ndim

2

In [58]:
arr2.dtype

dtype('int64')

### 类型推断：numpy会对数据类型进行一个较为合理的推断

In [60]:
arr = [["1","2",3,4],[5,6,7,8]]
arr2 = np.array(arr)
arr2

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U1')

In [61]:
# 查看 dtype
# <u1 unicode类型 字符串
arr2.dtype

dtype('<U1')

In [62]:
arr = [[1,2.2,3,4],[5,6,7,8]]
arr2 = np.array(arr)
arr2

array([[1. , 2.2, 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [63]:
# 查看 dtype
# float 浮点数
arr2.dtype

dtype('float64')

### numpy指定长度数组的创建


In [64]:
# 创建长度为10的数组，默认值为0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
# 创建长度为10的数组，默认值为1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
# 创建2*3的数组，默认值为1
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
# 创建空数组
# 注意 − 数组元素为随机值，因为它们未初始化。
np.empty(3)

array([0.e+000, 5.e-324, 1.e-323])

### arange 是range函数的数组版本

In [72]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [73]:
i = range(10)
type(i)

range

In [74]:
i

range(0, 10)

In [75]:
# 输出一个arange 
# arange = array range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 数据类型转换

In [76]:
arr = np.array([1.2,1.6,1.8,-2.3,-5.8])
arr

array([ 1.2,  1.6,  1.8, -2.3, -5.8])

In [78]:
arr.dtype
# float32/float64 双精度浮点数

dtype('float64')

In [79]:
# 转换为 int 
# int32 32位整型占4个字节
# int64 64位整形占8个字节
arr.astype(np.int32)

array([ 1,  1,  1, -2, -5], dtype=int32)

# 下一节 矢量化操作与广播运算