# Python科学运算2:矢量化操作与广播运算（练习版）
> 请在空格单元格输入


In [1]:
# 导包
import numpy as np

## 矢量化操作
数据在不需要编写循环的情况下就可以进行批量运算，这就叫矢量化操作
### 加法

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
# 请计算相加


In [3]:
arr1 = np.array([[1,2,3,4],[-3,2,4,9]])
arr2 = np.array([[5,6,7,8],[4,5,1,-10]])
# 请计算相加

### 减法


In [4]:
# 测试arr2-arr1

### 乘法

In [6]:
# 测试arr1*arr2

In [8]:
# 测试 5*arr1

### 除法

In [7]:
# 测试arr1/arr2

### 基本的索引和切片操作

In [9]:
# 初始化
arr =  np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 索引第三个

In [11]:
# 访问4及以后的元素

In [14]:
# 将一个标量的值赋这一个切片时，该值会自动的传播到整个区域，并且直接影响原数据的值
# 将 arr 前5个数改为 3


In [15]:
# 如果不想影响原数据操作
# 使用copy


In [16]:
# 访问2维数组
arr3 = np.array([[1,2,3,4],[-3,2,4,9]])
arr3

array([[ 1,  2,  3,  4],
       [-3,  2,  4,  9]])

In [17]:
# 读取第二行 [-3,  2,  4,  9]


In [18]:
# 读取第二行第一个


### 比较运算
- 在之前我们学习多条件运算时，我们使用的是and 和 or
- 使用numpy对象进行多条件的比较运算时，不能使用and和or
- 必须使用 &（and） 和 ｜（or）

In [20]:
names = np.array(['John','Tony','Jackie','Ben'])
names

array(['John', 'Tony', 'Jackie', 'Ben'], dtype='<U6')

In [21]:
names == "Tony"

array([False,  True, False, False])

In [22]:
# 选择 同时为 Tony 和 Ben

In [23]:
# 选择 Tony 或 Ben

### 花式索引（fancy indexing）